class Home_Page_Locators():
    samsung_s6 = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]/img[1]"
    Add_to_cart = "//a[contains(text(),'Add to cart')]"
    cart = "//a[@id='cartur']"
    ipone_name = "//td[contains(text(),'Iphone 6 32gb')]"

    nokia_lumi = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[2]/div[1]/a[1]/img[1]"
    nexus = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[3]/div[1]/a[1]/img[1]"
    sumaung_s7 = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[4]/div[1]/a[1]/img[1]"
    iphone_6 = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[5]/div[1]/a[1]/img[1]"
    sony_xphrie = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[6]/div[1]/a[1]/img[1]"
    htc_one = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[7]/div[1]/a[1]/img[1]"
    sony_vaio_5 = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[8]/div[1]/a[1]/img[1]"
    next_button = "//button[@id='next2']"
    assus_full_HD = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[5]/div[1]/a[1]/img[1]"
    Sony_name = "//td[contains(text(),'Sony vaio i5')]"
    phone_button = "//a[contains(text(),'Phones')]"
    laptop_button = "//a[contains(text(),'Laptops')]"
    monitor_button = "//a[contains(text(),'Monitors')]"
    makbook_air = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[3]/div[1]/a[1]/img[1]"
    sumsung_name = "//td[contains(text(),'Samsung galaxy s6')]"
    Apple_monitor = "//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]/img[1]"
    Apple_name = "//td[contains(text(),'Apple monitor 24')]"
    Nokia_lumi_delete = "//tbody/tr[1]/td[4]/a[1]"
